#!/usr/bin/env bash

sudo apt-get --yes --force-yes upgrade
sudo apt-get --yes --force-yes update

git clone https://github.com/wm-robo-ops/pi-clients.git ~
git clone https://github.com/wm-robo-ops/servos.git ~

git clone https://github.com/adafruit/Adafruit_Python_BNO055.git

sudo apt-get --yes --force-yes install vim
cp ./vimrc ~/.vimrc

sudo apt-get --yes --force-yes install gpsd gpsd-clients
sudo systemctl stop gpsd.socket
sudo systemctl disable gpsd.socket

sudo apt-get --yes --force-yes purge libreoffice-core libreoffice-common wolfram-engine minecraft-pi sonic-pi
sudo apt-get --yes --purge autoremove

cd Adafruit_Python_BNO055
sudo python setup.py install
sudo raspi-config nonint do_serial 1
sudo systemctl disable serial-getty@ttyAMA0.service

